services:
  - type: web
    name: blog-service
    env: node
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://blog-frontend-yvan.onrender.com
      - key: ADMIN_URL
        value: https://blog-admin-yvan.onrender.com
      - key: ALIYUN_OSS_REGION
        sync: false
      - key: ALIYUN_OSS_BUCKET
        sync: false
      - key: ALIYUN_OSS_ACCESS_KEY_ID
        sync: false
      - key: ALIYUN_OSS_ACCESS_KEY_SECRET
        sync: false
      - key: ALIYUN_OSS_ENDPOINT
        sync: false
