services:
  - type: web
    name: blog-service
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com,https://your-admin-domain.com
      - key: ALIYUN_OSS_REGION
        sync: false
      - key: ALIYUN_OSS_BUCKET
        sync: false
      - key: ALIYUN_OSS_ACCESS_KEY_ID
        sync: false
      - key: ALIYUN_OSS_ACCESS_KEY_SECRET
        sync: false
      - key: ALIYUN_OSS_ENDPOINT
        sync: false
      - key: ALIYUN_OSS_INTERNAL
        value: "false"
